### ISSUE TITLE
InputType

### ISSUE THREAD

**Issue by AndreBarciela** [reinaldoarrosi/MaskedEditText#1]
If I put inputType="number" in MaskedEditText it returns this error.
java.lang.RuntimeException: Unable to start activity ComponentInfo com.example.teste {/} com.example.teste.MainActivity: java.lang.IndexOutOfBoundsException: setSpan (0 ... 1) ends beyond length 0

Know the cause of this error?

**Comment by nicozimmermann94** [comment]
It seems like it does not work 100% as intended because if I set inputType to number, the numerical keyboard will not show up but the normal keyboard will.
