### ISSUE TITLE
Callback on format finished

### ISSUE THREAD

**Issue by nicozimmermann94** [reinaldoarrosi/MaskedEditText#13]
First: thank you very much for this!
Second: I think there is a need for a kind of callback when formatting is finished. When adding a second TextWatcher to the input (for example checking every char for a valid coupon code or something like that), the afterTextChanged method gets called multiple times because of reformatting. I cannot determine when your Watcher finishes formatting.

**Comment by reinaldoarrosi** [comment]
This issue is fixed in commmit 7d34a6d.

No need for an additional callback, you can now simply add another TextWatcher and it's methods will be called only once. This way you can pretend MaskedEditText is the same as EditText and use the same API for both.

**Comment by nicozimmermann94** [comment]
Thank you very very much!
