### ISSUE TITLE
Please release next version of library to maven repository with recent changes

### ISSUE THREAD

**Issue by TarasMazepa** [reinaldoarrosi/MaskedEditText#14]
Thanks

**Comment by reinaldoarrosi** [comment]
I'm currently working on issue #13 
I'll publish a new version to maven as soon as it is fixed.

**Comment by TarasMazepa** [comment]
😄

**Comment by reinaldoarrosi** [comment]
Version 1.1.0 is now available in JCenter and synced with Maven.
