### ISSUE TITLE
Cut/paste

### ISSUE THREAD

**Issue by irenecs** [reinaldoarrosi/MaskedEditText#4]
when you cut and paste  ,fail in this part

   if (charAllowed) {
                        isUserInput = false;

                            MaskedEditText.this.getText().replace(dstart, dstart + 1, "");

**Comment by reinaldoarrosi** [comment]
This appears to be the same problem as #5 .

You're not using the MaskedEditText from my repository, you're using it from this other repository (which has no relation with mine): https://github.com/pinball83/Masked-Edittext

Maybe you can open this issue on his repository...
