### ISSUE TITLE
crash when input non numeric characters

### ISSUE THREAD

**Issue by deeman30rus** [reinaldoarrosi/MaskedEditText#5]
<com.github.pinball83.maskededittext.MaskedEditText

        android:id="@+id/phone_number"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="24dp"
        android:layout_marginEnd="24dp"
        android:inputType="phone"
        android:digits="0123456789"
        android:hint="phone number"
        app:mask="+7 (999) 999 99-99"
        app:notMaskedSymbol="9"
        app:maskIconColor="@color/colorPrimary" />

if you start to type ',' chars, app will crash.

**Comment by reinaldoarrosi** [comment]
It appears that you're not using the MaskedEditText from my repository.

The code you used to open this issue seems to be from this other guy: https://github.com/pinball83/Masked-Edittext

Maybe you can open this issue on his repository...
